language: ruby
rvm:
  - 2.2.0
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build -r $CODECLIMATE_TEST_REPORTER_ID --exit-code $TRAVIS_TEST_RESULT
language: node_js
node_js:
  - 12.16.1
cache: npm
env:
  - CI=true
install:
  - npm ci
script:
  - npm run test:ci
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
