language: node_js
node_js:
  - 12.16.1
cache: npm

env:
  - CI=true

install:
  - npm ci

script:
  - npm run test:ci
  - npm run build

deploy:
  provider: netlify
  site: $NETLIFY_SITE
  auth: $NETLIFY_AUTH
  dir: 'build/'
